### ISSUE TITLE
Cobble Gen Randomizer causes ores to generate from cobblegens

### ISSUE THREAD

**Issue by mjevans** [EnigmaticaModpacks/Enigmatica8#238]
### Describe your suggestion

https://www.curseforge.com/minecraft/mc-mods/cobblegenrandomizer

As shipped it doesn't even drop the new vanilla MC copper ore, let alone any of the modded ores that would be nice.

### Why would you like this added/changed?

Generate all vanilla ores and most of the modded ones.

Dirt as the 'catalyst' block as the underside of the reaction has been added as a fallback for anyone that depends on the prior behavior.  I'd prefer to use soul_dirt for the nether, but that's vanilla behavior.

Notably:
* Skipped the Occultism specific ores; to retain a reason to use Occultism's miners if someone's in that mod as well as progression gating.
* Didn't include Thermal's Niter or Sulfur ores, I never use them and the small sample size I talked to haven't used them either.  They could be added for completeness.

The drop weight is just an initial guess, tuning / tweaking suggested.

``` TOML
# config/cobblegenrandomizer-common.toml
[general]
	use_config = true
	[general.lists]
		#Cobble gen
		block_list_cobble = [
			"minecraft:cobblestone|60",
			"minecraft:coal_ore|25",
			"minecraft:iron_ore|20",
			"minecraft:redstone_ore|20",
			"minecraft:lapis_ore|20",
			"minecraft:emerald_ore|5",
			"minecraft:gold_ore|10",
			"minecraft:diamond_ore|5",
			"minecraft:copper_ore|20",
			"create:zinc_ore|5",
			"ftbic:alluminum_ore|5",
			"ftbic:lead_ore|5",
			"ftbic:tin_ore|5",
			"thermal:silver_ore|5",
			"thermal:nickle_ore|2",
			"ae2:quartz_ore|2",
			"thermal:cinnabar_ore|1",
			"ftbic:uranium_ore|1",
			"ftbic:iridium_ore|1",
			"mekanism:osmium_ore|5"]
		#Stone gen == $stones +++ FIXME: Stone weights
		block_list_stone = [
			"minecraft:stone|30",
			"minecraft:granite|10",
			"minecraft:diorite|10",
			"minecraft:andesite|10",
			"minecraft:deepslate|30",
			"minecraft:calcite|5",
			"minecraft:tuft|5",
			"minecraft:dripstone|5",
			"create:asurine|1",
			"create:crimsite|1",
			"create:limestone|1",
			"create:ochrum|1",
			"create:scoria|1",
			"create:scorchia|1",
			"create:veridium|1",
			"quark:limestone|1",
			"quark:jasper|1",
			"quark:shale|1",
			"quark:myalite|1",
			"quark:dusky_myalite|1",
			"quark:permafrost|1",
			"byg:red_rock|1",
			"byg:rocky_stone|1",
			"byg:travertine|1",
			"byg:scoria_stone|1",
			"byg:soapstone|1",
			"minecraft:sand|1",
			"minecraft:red_sand|1",
			"byg:black_sand|1",
			"byg:blue_sand|1",
			"byg:purple_sand|1",
			"byg:windswept_sandstone|1",
			"byg:white_sand|1",
			"byg:ether_stone|1",
			"byg:purpur_stone|1"]
		#Basalt gen
		block_list_basalt = [
			"minecraft:basalt|60",
			"minecraft:blackstone|60",
			"minecraft:netherrack|60",
			"minecraft:nether_quartz_ore|30",
			"minecraft:nether_gold_ore|30",
			"minecraft:ancient_debris|1",
			"rftoolsbase:dimensionalshard_nether|1",
			"tconstruct:cobalt_core|1"]

		#Custom settings
		[general.lists.custom]
			# End stone generators?
			# Dirt under the generation area == Old vanilla (no copper) mod behavior
			custom_generators = [
				["cobblestone", "minecraft:end_stone", ["minecraft:end_stone|1"]],
				["stone", "minecraft:end_stone", ["minecraft:end_stone|1"]],
				["cobblestone", "minecraft:dirt", [
					"minecraft:cobblestone|60",
					"minecraft:coal_ore|25",
					"minecraft:iron_ore|20",
					"minecraft:redstone_ore|20",
					"minecraft:lapis_ore|20",
					"minecraft:emerald_ore|5",
					"minecraft:gold_ore|10",
					"minecraft:diamond_ore|5"]],
				["stone", "minecraft:dirt", [
					"minecraft:stone|30",
					"minecraft:granite|10",
					"minecraft:diorite|10",
					"minecraft:andesite|10"]],
				["basalt", "minecraft:dirt", [
					"minecraft:basalt|60",
					"minecraft:blackstone|60",
					"minecraft:netherrack|60",
					"minecraft:nether_quartz_ore|30",
					"minecraft:nether_gold_ore|30",
					"minecraft:ancient_debris|1"]]
			]
```

**Comment by NielsPilgaard** [comment]
I don't really understand this suggestion to be honest. You want cobblestone, stone and basalt generators to generate ores?

**Comment by mjevans** [comment]
They already generate SOME ores, notably the minecraft:dirt lists are the current behavior.

The mod's intent and functional use is as a different method of 'void mining', so I would like it to drop a more complete set of ores and stone types.

**Comment by Quezler** [comment]
it'll probably end up being way too easy, unless the catalyst blocks are e.g. expert milestones 🤔

**Comment by mjevans** [comment]
It's already this behavior, note how it already drops diamonds.  The only 'easier' thing is the dirt for the vanilla basalt gen, and that was just for consistency.  The dirt fallback could be dropped since I can't imagine many would complain about cobalt and dimensionalshard ore (the nether additions are MUCH less invasive).

``` TOML

#General settings
[general]
        #Use config instead of datapack
        use_config = true

        #List settings
        #Syntax: ["modid:block|weight"]
        #Example: ["minecraft:stone|2","minecraft:dirt|1"]
        #Forge tags are supported
        [general.lists]
                #Cobble gen
                block_list_cobble = ["minecraft:cobblestone|60", "minecraft:coal_ore|25", "minecraft:iron_ore|20", "minecraft:redstone_ore|20", "minecraft:lapis_ore|20", "minecraft:emerald_ore|5", "minecraft:gold_ore|10", "minecraft:diamond_ore|5"]
                #Stone gen
                block_list_stone = ["minecraft:stone|30", "minecraft:granite|10", "minecraft:diorite|10", "minecraft:andesite|10"]
                #Basalt gen
                block_list_basalt = ["minecraft:basalt|60", "minecraft:blackstone|60", "minecraft:netherrack|60", "minecraft:nether_quartz_ore|30", "minecraft:nether_gold_ore|30", "minecraft:ancient_debris|1"]

                #Custom settings
                [general.lists.custom]
                        #Custom generators
                        #Syntax: [gen]
                        #Gen: [type, block, list]
                        #Type: cobblestone, stone
                        #Block: resource location of the block below the generated block
                        #List: see List settings
                        #Examples:
                        #custom_generators = [
                        #   ["cobblestone", "minecraft:diamond_block", ["minecraft:diamond_block"]],
                        #   ["cobblestone", "minecraft:dirt", ["forge:dirt"]],
                        #   ["cobblestone", "minecraft:white_wool", ["minecraft:wool"]]]
                        custom_generators = []
```
